### ISSUE TITLE
Create UnityDAO flow

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#54]
We need to create a new flow to create DAOs. The app will have two different ways to create DAOs.

- UnityDAO: For communities that want to share the treasury and vote for each action in the DAO, using governance token
- SmartDAO: For people that want to create a dao where only a few members vote 

We are going to start with UnityDAO flow. Will be similar to the current /create flow but we want to make it easier and simpler.

To do so, we want to implement just three screens.

When the user clicks create UnityDAO goes to /createUnity and there is a screen with the main required fields, you can use the same icons and style as create for now

![Image](https://github.com/Libree/frontend/assets/974720/1c6cc9bb-5ce5-40e4-b101-5fcce27674bb)

Then after clicking next a new page opens with the info associated with the token, but now we know that will be a token holders mode so we can omit these fields and just show this

![Image](https://github.com/Libree/frontend/assets/974720/e4c98eaf-4525-4a35-ac68-d398d10bb5b4)

These are all the required fields, but still, fields related to voting are needed, we are going to show them but filled with default data. 

To show them on this second page, we will show before the next button a field like this that can be expanded call 'Advanced'

![Image](https://github.com/Libree/frontend/assets/974720/5b438a8c-0e72-4172-b936-7802367b24e1)

And inside it all the fields related to governance 

![Image](https://github.com/Libree/frontend/assets/974720/2fbbe7cb-d164-4c1b-bcda-d674b7b346aa)

An example of this can be checked in any dao at settings/edit

In the last view, we will show the summary as now. 

All these views should be mobile-compatible as of now.

**Comment by ialberquilla** [comment]
@valentinnavalos  Looks great! Some small fixes

- We can remove this page and go directly to the next one



![Image](https://github.com/Libree/frontend/assets/974720/9925703e-ac24-429c-91f2-504b4691198e)

- This governance advanced dropdown should be part of the previous page

Here



![Image](https://github.com/Libree/frontend/assets/974720/1623da3e-eca0-47cf-acf5-82960d9b8af7)

The idea is to have a two steps journey

**Comment by valentinnavalos** [comment]
Done. 

PR: https://github.com/Libree/frontend/pull/71

**Comment by ialberquilla** [comment]
That should be Mumbai and goerli


![Image](https://github.com/Libree/frontend/assets/974720/26c0416a-4810-458e-80f8-a37f65a2d97b)


Actually, we can remove goerli and leave only Mumbai

**Comment by ialberquilla** [comment]
Creation is not working, looks like a field is missing or maybe the way to find the plugin. 



![Image](https://github.com/Libree/frontend/assets/974720/43de7731-f28a-436d-8cb6-78a24017ea1c)



You can compare this flow, with the /createFlow to see what's different. If you console.log this variable in both flows you should see the difference

https://github.com/Libree/frontend/blob/828216924966883f55b569af83317ab6350e1440/packages/web-app/src/context/createDao.tsx#L78

**Comment by valentinnavalos** [comment]
Yes. There is an issue when the `minimumApproval` and `minimumParticipation` variables are submitted.
This problem occurs when the user does not modify the 'Advanced' dao config, causing those variables to be sent as NaN.

Also, i noticed that even the `daoName` and `daoSumamary` variables are filled, both are received as undefined.

**Comment by valentinnavalos** [comment]
> Creation is not working, looks like a field is missing or maybe the way to find the plugin.
> 
> ![Image](https://user-images.githubusercontent.com/974720/253959565-43de7731-f28a-436d-8cb6-78a24017ea1c.png)
> 
> You can compare this flow, with the /createFlow to see what's different. If you console.log this variable in both flows you should see the difference
> 
> https://github.com/Libree/frontend/blob/828216924966883f55b569af83317ab6350e1440/packages/web-app/src/context/createDao.tsx#L78

Fixed.

PR: https://github.com/Libree/frontend/pull/99

**Comment by ialberquilla** [comment]
Still failing with same error  I'm selecting all the plugins to be installed

**Comment by valentinnavalos** [comment]
With this PR (https://github.com/Libree/frontend/pull/105) it seems to be working. However, it threw an error due to an undefined value for `aavePoolAddress` in encoding.ts

**Comment by ialberquilla** [comment]
This error comes because on the first page if testnet is not checked the network shown is production not finding the aave pool for this network



![Image](https://github.com/Libree/frontend/assets/974720/6a1e54f4-d942-4f27-b4b3-a5ee6865dc63)


Testnet should be always checked

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/111
